### ISSUE TITLE
Are we rendering images correctly?

### ISSUE THREAD

**Issue by stevelandeyasana** [Asana/Drawsana#10]
This person seems not to think so: https://github.com/tetek/Drawsana/commit/d2620ef791950169d44628f0eb8b5739ef7ec8af

**Comment by stevelandeyasana** [comment]
I verified that we are not creating images of increasing size. This is not our bug @tetek

**Comment by echamussy** [comment]
Hi @stevelandeyasana, I'm also having the same issue with the scale factor. The fixed proposed by @tetek works by having 1 instead of 0 for the scale parameter here:

`class func renderImage(size: CGSize, _ code: (CGContext) -> Void) -> UIImage? {
    UIGraphicsBeginImageContextWithOptions(size, false, 1)`

According to the documentation: "The scale factor to apply to the bitmap. If you specify a value of 0.0, the scale factor is set to the scale factor of the device’s main screen.". This is important when you have a background image as the result image is 3x the original resolution (on iPhone 7+ and other devices with 3x screen density).

If you'd like I can make a PR to fix this. Cheers and THANKS for your awesome work!

**Comment by stevelandeyasana** [comment]
I support making it configurable, and a PR would be great! It's very important that we continue to be able to use device native resolutions for drawings and not go non-retina on everything, but people with different use cases should have their needs met.
